<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_Cart_Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8bfaa13c-5e67-48c0-91d5-5a30f37cc66e</testSuiteGuid>
   <testCaseLink>
      <guid>8e52b75b-960d-4452-9f6f-7d402c93978f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Amazon/TC_shopping_cart</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>931c962b-73dc-4076-99dc-99640171dde0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_Cart_Excel/Amazon_Excel_Cart</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c3875cc-2895-4b10-8181-36e0d690e135</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2759b2b4-cd1e-4b3e-aa33-d6901192db05</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
